version: 2.1
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - test
      - build:
          requires:
            - test
      # - packages
      - terraform/fmt:
          checkout: true
          context: terraform
          requires:
            - build
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
      # - deploy-app:
      #     context: terraform
      #     requires:
      #       - terraform/apply

jobs:
  build:
    environment:
      CHROME_BIN: 'C:\Program Files\Google\Chrome\Application\chrome.exe'
    docker:
      - image: cimg/node:16.10
    # parallelism: 4
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: npm install
      - run: npm run build
      - run: echo "CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe" >> $BASH_ENV
      - run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker build -t my-angular-app .
      - run: docker tag my-angular-app $DOCKER_LOGIN/my-angular-app
      - run: docker push $DOCKER_LOGIN/my-angular-app
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - run: 
          name: Install Chrome
          command: |
              apt-get update
              apt-get install -y google-chrome-stable
      - run: echo 'export CHROME_BIN=/usr/bin/google-chrome-stable' >> $BASH_ENV
      - run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI


  terraform/fmt:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: terraform fmt -check=true -diff=true
  terraform/validate:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: terraform validate
  terraform/plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: terraform plan
  terraform/apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: terraform apply

  # deploy-app:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - run: ssh -i ~/projet/pk_UBUNTU.pem terraform@$EC2_PUBLIC_IP "docker stack deploy -c ~/project/docker-compose.yml my-angular-app"
